spring:
  messages:
    basename: i18n/message
    encoding: utf-8
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    logSlowSql: true
    url: jdbc:mysql://127.0.0.1:3306/cadp_db?useUnicode=true&characterEncoding=utf-8
    username: user01
    password: HJJDHSUDHndjashjhj@293387YYbdsd
  jpa:
    # 显示sql
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
  #redis配置
  redis:
    database: 11
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
    testOnBorrow: true

# 日志配置
log:
  path: /data/logs/
  level: info